services:
  db:
    image: postgres:17
    container_name: patient-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-patientdb}"]
      interval: 10s
      timeout: 5s
      retries: 1

    networks:
      - hospital   

  kafka:
    image: apache/kafka:latest
    container_name: kafka

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,INTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - hospital

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: hospital.net

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${DOCKER_KAFKA_SERVER}

    networks:
      - hospital  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    restart: on-failure:1  

    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started  

    environment:
      SERVER_PORT: ${SERVER_PORT}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
      DB_URL: ${DOCKER_POSTGRES_URL}
      DB_USERNAME: ${DOCKER_POSTGRES_USER}
      DB_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      DB_PLATFORM: ${DB_PLATFORM}
      BILLING_SERVICE_ADDRESS: ${DOCKER_BILLING_SERVICE_ADDRESS}
      BILLING_SERVICE_GRPC_PORT: ${DOCKER_BILLING_SERVICE_GRPC_PORT} 
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_KAFKA_SERVER}

    networks:
      - hospital

volumes:
  pgdata:

networks:
  hospital:
    external: true