version: "3.9"

services:
  db:
    image: postgres:17
    container_name: patient-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-patientdb}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-patientdb}"]
      interval: 10s
      timeout: 5s
      retries: 1
    networks:
      - hospital   
      
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - hospital

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    networks:
      - hospital  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    restart: on-failure:1  
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started  
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://db:5432/patientdb}
      DB_USERNAME: ${DB_USERNAME:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_DRIVER: ${DB_DRIVER:-org.postgresql.Driver}
      DB_PLATFORM: ${DB_PLATFORM:-org.hibernate.dialect.PostgreSQLDialect}
      BILLING_SERVICE_ADDRESS: ${BILLING_SERVICE_ADDRESS:-billing-service}
      BILLING_SERVICE_GRPC_PORT: ${BILLING_SERVICE_GRPC_PORT:-9001} 
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - hospital

volumes:
  pgdata:

networks:
  hospital:
    external: true