spring.config.import=optional:file:.env[.properties]

spring.application.name=patient-service
server.port=${SERVER_PORT}
grpc.server.port=${GRPC_SERVER_PORT}


# postgres properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.database-platform=${DB_PLATFORM}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# kafka properties
billing.service.address=${BILLING_SERVICE_ADDRESS}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
