services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing-service
    restart: on-failure:1  
    environment:
      SERVER_PORT: ${SERVER_PORT:-4002}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT:-9002}
    networks:
      - hospital

networks:
  hospital:
    external: true
      
